import type { Metadata } from "next";
import { Inter } from "next/font/google";
// css
import "@/public/css/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NEXT TEMPLATE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="max-width">{children}</div>
      </body>
    </html>
  );
}
