import type { Metadata } from "next";
// css
import "@/public/css/global.css";

export const metadata: Metadata = {
  title: "NEXT TEMPLATE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="max-width">{children}</div>
      </body>
    </html>
  );
}
